### ISSUE TITLE
Text color and tab styling issues in Obsidian 1.0

### ISSUE THREAD

**Issue by bholmesdev** [cassidoo/cardstock#4]
Hey! Long-time cardstock user here. I just bumped to the new Obsidian 1.0 release, and noticed this theme has some visual bugs:
- Text is a lighter gray in "edit" mode, though a normal solid color in "preview" mode
- Tab colors awkwardly clip into the top menu bar
- The page title is sans-serif rather than serif. If you're wondering where that title came from like I was: obsidian now auto-generates page titles based on file name, instead of having to add an `h1` by hand.

**Cardstock in Obsidian 1.0**

<img width="714" alt="image" src="https://user-images.githubusercontent.com/51384119/196043070-e7e08435-8cd4-4571-8ab6-1da12fc62b8a.png">

**Reference: default theme in Obsidian 1.0**

<img width="711" alt="image" src="https://user-images.githubusercontent.com/51384119/196043115-f9497efc-3e88-447f-bf4e-2c2e86029c8a.png">

**Comment by cassidoo** [comment]
Adding this for myself:
https://forum.obsidian.md/t/1-0-theme-migration-guide/42537

**Comment by cassidoo** [comment]
Heads up @bholmesdev a majority of the style fixes are in place, gotta clean up the menu stuff but it's actually usable again!!

**Comment by cassidoo** [comment]
This is shipped!

**Comment by bholmesdev** [comment]
> This is shipped!

Woo, thanks Cassidy! Just updated and it looks lovely now 👏
