### ISSUE TITLE
Add installation instructions for Obsidian noobs? 😅

### ISSUE THREAD

**Issue by richardziegler** [cassidoo/cardstock#5]
I couldn't figure out how to install this theme and googling around showed me several different instructions but it didn't work.

Would love some step-by-step instructions on the README. 😊

**Comment by cassidoo** [comment]
Ahh I'll add those! I still have to update it for the latest version so it might not be coming up in the Community Themes listing, too.

**Comment by richardziegler** [comment]
Thank you! I didn't see it within the themes listed in the app, no. So once that is done it is pretty self explanatory. :)
