### ISSUE TITLE
Font Headings is set to "Source Serif" and not "Source Serif 4"

### ISSUE THREAD

**Issue by johnsbuck** [cassidoo/cardstock#6]
The fonts linked in the README.md are **_Source Serif 4_** and **_DM Sans_**. While DM Sans is correct in _**theme.css**_, Source Serif 4 is improperly listed, leading to headings not using the correct font.

To fix, either replace **_Source Serif_** with _**Source Serif 4**_, or add **_Source Serif 4_** as an additional font.

**Comment by cassidoo** [comment]
Thank you, fixed!
